Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 7, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/__main__.py", line 58, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/webserver_command.py", line 485, in webserver
    run_command_with_daemon_option(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/daemon_utils.py", line 80, in run_command_with_daemon_option
    callback()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/webserver_command.py", line 488, in <lambda>
    callback=lambda: start_and_monitor_gunicorn(args),
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/webserver_command.py", line 471, in start_and_monitor_gunicorn
    gunicorn_master_proc = psutil.Process(gunicorn_master_proc_pid)
  File "/home/airflow/.local/lib/python3.10/site-packages/psutil/__init__.py", line 317, in __init__
    self._init(pid)
  File "/home/airflow/.local/lib/python3.10/site-packages/psutil/__init__.py", line 363, in _init
    raise NoSuchProcess(pid, msg=msg) from None
psutil.NoSuchProcess: process PID not found (pid=56537)
